"""Vakula: terminal-native, defensive situational awareness tooling."""

# Vakula is a terminal application, not a library that benefits from keeping
# generated bytecode in the user's workspace. Set this before submodules load.
import sys

sys.dont_write_bytecode = True

__version__ = "0.2.0"
